---
- name: USE ACI REST MODULE
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - name: SEARCH A TENANT
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        method: "get"
        path: "api/mo/uni/tn-asd.json"
